### ISSUE TITLE
one question about scaling of images

### ISSUE THREAD

**Issue by johnniewalker3** [Saafke/FSRCNN_Tensorflow#5]
Hi again Saafke,
i wanted to quest you something.When we augment our data using scaling with 0.6 , 0.7, 0.8, 0.9 factor then we have to downscale them again with the scale factor(2 or 3 or 4) to produce the training data?

**Comment by Saafke** [comment]
Hi johnnie,

Yes, you are right. As a **first step**, we do data augmentation, with as only goal to generate more diverse training data. In the original paper they do:
1. resizing the images with scale-factors 0.6, 0.7, 0.8, 0.9 (more variation because of the downscaling)
2. rotating the images (more variation because the images are in different orientations)

The **second step** is to actually build the training dataset. That is, to create the input-output pairs. Remember that our task is to increase the resolution for images. So the network should learn to do this. We therefore create input-output pairs, where the input will be the smaller resolution images, and the output will be the higher resolution images. We already have the higher resolution images (the normal images, our result from step 1), so to create the corresponding lower resolution images, we just downscale them again by the desired factors (2, 3 and 4) in this case. 

Then during training, we can feed as input the lower-resolution images to the network. The output or ground-truth images (that the network will learn to predict) will be the corresponding higher-resolution images. The network will then learn to up-scale images by a scale factor of 2, 3 or 4. 

Hope it makes sense. Let me know if it's unclear.
